language: go
sudo: required
go_import_path: cirello.io/bookmarkd
go:
  - "1.x"

services:
  - docker

before_install:
  - docker run -d -p 8000:8000 dwmkerr/dynamodb

script:
  - go get -u golang.org/x/vgo
  - vgo test -v ./...