language: go
sudo: required
go_import_path: cirello.io/pglock
go:
  - "1.11"

services:
  - postgresql

install: true

before_script:
  - psql -c 'create database locktest;' -U postgres

script:
  - go test -v ./...