---
ucirello/public:
  environment:
  - AWS_ACCESS_KEY_ID="FAKE-AKIAIH6BUPODEOU2DXNQ"
  - AWS_SECRET_ACCESS_KEY="FAKE-ZzwT95GE8mbC5c73lEiuBLGZV+/u8Z2PJK/cF8PJ"
  - CC=gcc
  commands: |
    docker rm -f dynamoDB || echo "dynamoDB not present"
    docker run -d --name dynamoDB -p 8000:8000 dwmkerr/dynamodb

    vgo test -v ./...

    ./scripts/export-mirrors.sh
    docker rm -f dynamoDB
    docker system prune -f
    echo "OK"